"""Initial migration after dropping database

Revision ID: 4971da213a72
Revises: 
Create Date: 2025-05-05 11:31:39.669390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4971da213a72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=150), nullable=False),
    sa.Column('lastName', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('profile_picture_filename', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_image_url', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_item', sa.Float(), nullable=False),
    sa.Column('total_item_price', sa.Float(), nullable=False),
    sa.Column('delivered_date', sa.DateTime(), nullable=False),
    sa.Column('taste_selection', sa.String(length=500), nullable=True),
    sa.Column('recommended_selection', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('order_total_price', sa.Float(), nullable=False),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('users')
    # ### end Alembic commands ###
